### ISSUE TITLE
Add web scraping codes using Beautiful Soup

### ISSUE THREAD

**Issue by GrayFlash** [TheAlgorithms/Jupyter#14]
Can I add scraping codes for few news sites, imdb and Netflix as a part of automation directory??

**Comment by cclauss** [comment]
Sure...  There are some examples to look at in https://github.com/TheAlgorithms/Python/tree/master/web_programming

**Comment by GrayFlash** [comment]
@cclauss can you label this repo for hacktoberfest and review my PR with the label. The guidelines for hacktoberfest has been updated (https://hacktoberfest.digitalocean.com/hacktoberfest-update).

**Comment by GrayFlash** [comment]
@cclauss I made another PR for Netflix one, can you review it.

**Comment by hritik5102** [comment]
> @cclauss I made another PR for Netflix one, can you review it.

@GrayFlash ok, I'll look into your code
