### ISSUE TITLE
Add some machine learning algorithms 

### ISSUE THREAD

**Issue by m607stars** [TheAlgorithms/Jupyter#17]
Can I add some machine learning algorithms which aren't there in the current repository?
1. Linear Regression using numpy, pandas and scikit
2. Logistic Regression using numpy, pandas and scikit
3. SVMs using scikit
4. Decision trees using scikit

**Comment by amoghatsunil** [comment]
i would like to add K means clustering to this repo

**Comment by hritik5102** [comment]
> Can I add some machine learning algorithms which aren't there in the current repository?
> 
> 1. Linear Regression using numpy, pandas and scikit
> 2. Logistic Regression using numpy, pandas and scikit
> 3. SVMs using scikit
> 4. Decision trees using scikit

@m607stars ok, go ahead but make sure your code should be documented properly and add only one algorithm per PR.
so if you want to add more, create a separate issue.

Thank you :)

**Comment by hritik5102** [comment]
> i would like to add K means clustering to this repo

@amoghatsunil please create a separate issue. 
Thank you :)

**Comment by snehad88** [comment]
I would like to add LDA

**Comment by hritik5102** [comment]
Sure go ahead @snehad88

**Comment by aishwarya24bhagwat** [comment]
Can I please add machine learning algorithms that are not in the current repository? for example XGBoost or Boost classifier? I want to make an open source contribution, Thanks!

**Comment by hritik5102** [comment]
@aishwarya24bhagwat yes, go ahead 🙌🏻

**Comment by hritik5102** [comment]
@void-02 yes please go ahead 👍

**Comment by gemini30** [comment]
can I add naive bayes algorithm fir classification?
