### ISSUE TITLE
Add some numerical methods algorithms

### ISSUE THREAD

**Issue by CheshirLvova** [TheAlgorithms/Jupyter#26]
Can I add some numerical methods algorithms which aren't there in the current repository?

- [x]  Euler's method for the Cauchy problem
- [x]  The Rectangular method 
- [x]  The Trapezium method 
- [x]  The Simpson’s method 
- [x]  Method of tangents

**Comment by hritik5102** [comment]
@CheshirLvova ok, go ahead but make sure your code should be documented properly and add only one algorithm per PR.
so if you want to add more, create a separate issue.

Please create a new folder called - "**Numerical methods**" and add your algorithm there, also mention the issue after making any PR.

**Thanks you :)**

**Comment by CheshirLvova** [comment]
@hritik5102  could you review and maybe approve my pull requests if everything ok, please?)

**Comment by hritik5102** [comment]
> @hritik5102 could you review and maybe approve my pull requests if everything ok, please?)

Expecting a more detailed explanation of the work you have done, but it's ok for now, bcoz the algorithm was not that complex.
Congo your PR has been merged 🎉

Thanks for your contribution :)

**Comment by kunyaw12** [comment]
@hritik5102 can u help me to review my code , and approve it if everything okay?
 please

**Comment by hritik5102** [comment]
Hello, @kunyaw12. can you please mention which PR to review? because you've created multiple pull requests, it's difficult to review all of them.

**Comment by hritik5102** [comment]
@kunyaw12 why you've created 2 pull requests #51 and #52 for classes and objects? Before contributing anything to the project, you've to create an issue mentioning the algorithm and other necessary details. please read the `contribution guidelines` carefully then only created any pull request. I'm closing both the `pull request`.

**Comment by hritik5102** [comment]
Closing this issue for now
